version: '3.8'

services:
  vigilancia-front-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: development
        API_BASE_URL: ${API_BASE_URL}
        RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
    ports:
      - "4200:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - vigilancia-network

  vigilancia-front-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
        API_BASE_URL: https://api.vigilancia.com.br
        RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - vigilancia-network

networks:
  vigilancia-network:
    driver: bridge